#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc/dev/rules.d to facilitate bringing"
echo ""

sudo cp `rospack find zmcrobot_ros`/55-zmcrobot-arduino.rules /etc/udev/rules.d

echo ""
echo "restarting udev"
echo ""

sudo service udev reload
sudo service udev restart
